image: maven:3-eclipse-temurin-21

# --- CONFIGURATION OBLIGATOIRE ÉCOLE ---
# (Sans ça, rien ne marche sur le réseau de l'école)
variables:
  MAVEN_CLI_OPTS: "--batch-mode -s settings.xml -Dmaven.repo.local=libs"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - "libs"
    - "**/target"

before_script:
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd"><mirrors><mirror><id>ensisa</id><name>Nexus ENSISA</name><url>https://nexus.cluster.ensisa.uha.fr/repository/maven-public/</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>' > settings.xml

stages:
  - build_and_test

# --- LE SEUL JOB (Pour l'instant) ---
build_job:
  stage: build_and_test
  script:
    # 1. On nettoie tout
    # 2. On installe les dépendances
    # 3. -DskipITs : On NE LANCE PAS les tests d'intégration (Selenium) pour l'instant
    # 4. spotbugs:check : On lance l'analyseur de qualité
    - mvn $MAVEN_CLI_OPTS clean install -DskipITs spotbugs:check

    # Génération du rapport de couverture (pour le badge GitLab)
    - "grep -v 'COMPLEXITY_MISSED,COMPLEXITY_COVERED' kanbin-projest-reporting/target/site/jacoco-aggregate/jacoco.csv | awk -F, '{missed += $10 ; covered += $11} END {print \"Jacoco Coverage:\", 100*covered/(covered+missed), \"%\"}'"

  artifacts:
    expire_in: 1 hour
    when: always # On garde les rapports MÊME si ça plante
    reports:
      junit: "**/target/surefire-reports/TEST-*.xml"
    paths:
      - "**/target/surefire-reports"
      - "**/target/spotbugs.xml"