image: maven:3-eclipse-temurin-21

# --- CONFIGURATION GLOBALE ---
variables:
  MAVEN_CLI_OPTS: "--batch-mode -s settings.xml -Dmaven.repo.local=libs"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - "libs"
    - "**/target"

before_script:
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd"><mirrors><mirror><id>ensisa</id><name>Nexus ENSISA</name><url>https://nexus.cluster.ensisa.uha.fr/repository/maven-public/</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>' > settings.xml

stages:
  - build_and_test
  - integration

# --- ÉTAPE 1 : BUILD & QUALITÉ ---
build_job:
  stage: build_and_test
  script:
    # 1. Compile et installe les JARs dans le cache "libs"
    # 2. Lance SpotBugs (Qualité)
    # 3. Pré-télécharge Failsafe pour l'étape suivante
    - mvn $MAVEN_CLI_OPTS clean install -DskipITs spotbugs:check failsafe:help

    # Rapport de couverture
    - "grep -v 'COMPLEXITY_MISSED,COMPLEXITY_COVERED' kanbin-projest-reporting/target/site/jacoco-aggregate/jacoco.csv | awk -F, '{missed += $10 ; covered += $11} END {print \"Jacoco Coverage:\", 100*covered/(covered+missed), \"%\"}'"
  artifacts:
    expire_in: 1 hour
    reports:
      junit: "**/target/surefire-reports/TEST-*.xml"
    paths:
      - "**/target/*.war"
      - "**/target/classes"
      - "**/target/test-classes"
      # On laisse "libs" dans le cache, pas besoin de l'uploader en artefact

# --- ÉTAPE 2 : TESTS D'INTÉGRATION (SELENIUM) ---
integration_test_job:
  stage: integration
  script:
    # ASTUCE : On installe Chrome DANS ce conteneur.
    # Plus de problèmes de réseau, tout se passe en local.
    - apt-get update && apt-get install -y chromium chromium-driver

    # Lancement des tests d'intégration.
    # Note : On n'active PAS le mode "remote" (-Dselenium.remote...),
    # donc ton code AbstractIT va utiliser le Chrome local qu'on vient d'installer.
    - mvn $MAVEN_CLI_OPTS failsafe:integration-test failsafe:verify -Dsurefire.skip=true
  dependencies:
    - build_job