image: maven:3-eclipse-temurin-21

# 1. SETUP DU PROF (OBLIGATOIRE)
before_script:
  - echo '<settings
    xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
    <mirror>
    <id>ensisa</id>
    <name>Nexus ENSISA</name>
    <url>https://nexus.cluster.ensisa.uha.fr/repository/maven-public/</url>
    <mirrorOf>*</mirrorOf>
    </mirror>
    </mirrors>
    </settings>' > settings.xml

variables:
  MAVEN_CLI_OPTS: "--batch-mode -s settings.xml -Dmaven.repo.local=libs"

# 2. LE CACHE (Le secret de la réussite)
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - "libs"       # On garde les dépendances téléchargées
    - "**/target"  # On garde les résultats de compilation

stages:
  - build_and_test

# 3. LE JOB UNIQUE (Build + TU + SpotBugs)
# On fusionne 'compile' et 'test' pour respecter "1 Build"
build_job:
  stage: build_and_test
  script:
    # On ajoute 'failsafe:help' pour pré-télécharger le plugin d'intégration dans 'libs'
    # On ajoute 'spotbugs:check' pour la qualité
    - mvn $MAVEN_CLI_OPTS clean install -DskipITs spotbugs:check failsafe:help

    # Génération du badge de couverture
    - grep -v 'COMPLEXITY_MISSED,COMPLEXITY_COVERED' kanbin-projest-reporting/target/site/jacoco-aggregate/jacoco.csv | awk -F, '{missed += $10 ; covered += $11} END {print "Jacoco Coverage:", 100*covered/(covered+missed), "%"}'

  coverage: '/Jacoco Coverage:\s+\d+[,\.]?\d+\s+\%/'

  artifacts:
    expire_in: 1 hour
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
    paths:
      # On ne prend QUE ce qui est nécessaire pour éviter l'erreur "Too Large"
      - "**/target/*.war"
      - "**/target/classes"
      - "**/target/test-classes"
      - "kanbin-projest-reporting/target/site/jacoco-aggregate/*"
      - "**/target/spotbugs.xml"