services:
  kanbin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanbin-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - kanbin-net

networks:
  kanbin-net:
    name: kanbin-net
